image: marcopeg/gitpod-workspace-postgres:2.5.0

tasks:
  - name: Unit Tests
    init: sleep 30
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    init: sleep 30
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after
  - name: Api
    init: yarn install
    command: yarn start:gitpod:api
    openIn: bottom
    openMode: tab-after
  - name: App
    init: sleep 30
    command: yarn start:gitpod:app
    openIn: bottom
    openMode: split-right

ports:
  - port: 5432
    onOpen: ignore
  - port: 8008
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 3000
    onOpen: ignore
