tasks:
  - name: App.
    init: yarn install
    command: yarn start
    openIn: right
  - name: Unit Tests
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after

ports:
  - port: 8080
    onOpen: ignore
