image: marcopeg/gitpod-workspace-postgres:2.5.0

tasks:
  - name: E2E Tests
    init: sleep 30
    command: yarn tdd:e2e
    openIn: bottom
  - name: Unit Tests
    init: sleep 30
    command: yarn tdd:unit
    openIn: bottom
    openMode: split-right
  - name: App.
    init: yarn install
    command: yarn start
    openIn: bottom
    openMode: split-right

ports:
  - port: 5432
    onOpen: ignore
  - port: 8008
    onOpen: ignore
  - port: 8080
    onOpen: ignore
