image: gitpod/workspace-postgres

tasks:
  - name: Adminer
    before: mkdir -p ${GITPOD_REPO_ROOT}/public
    init: wget -O ${GITPOD_REPO_ROOT}/public/index.php https://github.com/vrana/adminer/releases/download/v4.7.6/adminer-4.7.6-en.php
    command: apachectl start
  - name: App.
    init: yarn install
    command: yarn start
    openIn: right
  - name: Unit Tests
    command: yarn tdd:unit
    openIn: right
    openMode: tab-after
  - name: E2E Tests
    command: yarn tdd:e2e
    openIn: right
    openMode: tab-after

ports:
  - port: 8001
    onOpen: ignore
  - port: 8080
    onOpen: ignore
