tasks:
  - init: yarn install
    command: yarn start
  - command: yarn tdd:e2e
    openIn: bottom
    openMode: tab-after
  - command: yarn tdd:unit
    openIn: bottom
    openMode: tab-after

ports:
  - port: 8080
    onOpen: ignore
